### PR TITLE
FIX: Issue #11 keywords issue

### PR DESCRIPTION
**Pull request by roopamjain01**

### CODE REVIEW

**Comment by roopamjain01** [comment]
To fix the issue I have updated 2 php file.

(1) ParseXML2MCPcommand.php updated line number 174 : Collect keyword value into associated array and assigned that associated array into keywords array.

(2) MDMetadata.php added new lines 380 to 393 : If relation type is 'MDKeywords', then loadData() into MDKeyword dataobject and add that object into $relObj.

If you need same changes into Xsl files also, then please let me know.

**Comment by roopamjain01** [comment]
Hi
Can you please add this latest commit to the packagist(https://packagist.org/packages/silverstripe/geocatalogue), just because I am not able to get latest commit via composer.

**Comment by dhensby** [comment]
@silverstripe-archive/core-team / @stojg  Does any one have admin access on packagist to ensure the integration is up to date?

**Comment by tractorcow** [comment]
I've tried to trigger a service update on the github end, but it doesn't seem to work. Need @stojg to step in sorry.

If you could, please add myself and @dhensby to admins. We will add other core members as well.

**Comment by stojg** [comment]
Sorry, this got hidden in the heap of all notices. I've add @dhensby  and @tractorcow as maintainer on packagist and ran a update.

**Comment by dhensby** [comment]
thanks @stojg 

@roopamjain01 packagist is now up to date :)

**Comment by roopamjain01** [comment]
Thanks @dhensby

**Pull request merged**
